FROM golang:1.19-alpine3.16

RUN apk add git --no-cache

RUN go install golang.org/x/tools/gopls@latest

RUN adduser vscode -s /bin/sh -D \
	&& addgroup docker \
	&& addgroup vscode docker

ENV GOPATH /home/vscode/go
ENV GOMODCACHE /home/vscode/go/pkg/mod

USER vscode