name: Bot

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build
        run: go build -v ./...
  
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Test
        run: go test -v ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          skip-go-installation: true
          skip-pkg-cache: true
          skip-build-cache: true
